// Mocks generated by Mockito 5.4.4 from annotations
// in artisanarc/test/business/daily_sales_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:artisanarc/features/business/data/business_repository.dart'
    as _i2;
import 'package:artisanarc/features/business/data/sale_model.dart' as _i4;
import 'package:artisanarc/features/inventory/data/inventory_model.dart' as _i6;
import 'package:artisanarc/features/inventory/data/inventory_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BusinessRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessRepository extends _i1.Mock
    implements _i2.BusinessRepository {
  MockBusinessRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createSale(_i4.SaleRecord? sale) => (super.noSuchMethod(
        Invocation.method(
          #createSale,
          [sale],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSale(_i4.SaleRecord? sale) => (super.noSuchMethod(
        Invocation.method(
          #updateSale,
          [sale],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.SaleRecord>> getSales() => (super.noSuchMethod(
        Invocation.method(
          #getSales,
          [],
        ),
        returnValue: _i3.Future<List<_i4.SaleRecord>>.value(<_i4.SaleRecord>[]),
      ) as _i3.Future<List<_i4.SaleRecord>>);

  @override
  _i3.Future<void> deleteSale(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSale,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i5.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addItem(_i6.InventoryItem? item) => (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.InventoryItem?> getItemById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getItemById,
          [id],
        ),
        returnValue: _i3.Future<_i6.InventoryItem?>.value(),
      ) as _i3.Future<_i6.InventoryItem?>);

  @override
  _i3.Future<List<_i6.InventoryItem>> getAllItems() => (super.noSuchMethod(
        Invocation.method(
          #getAllItems,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.InventoryItem>>.value(<_i6.InventoryItem>[]),
      ) as _i3.Future<List<_i6.InventoryItem>>);

  @override
  _i3.Future<void> updateItem(_i6.InventoryItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
