// Mocks generated by Mockito 5.4.4 from annotations
// in artisanarc/test/inventory/inventory_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:artisanarc/features/inventory/data/inventory_model.dart' as _i4;
import 'package:artisanarc/features/inventory/domain/inventory_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [InventoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryService extends _i1.Mock implements _i2.InventoryService {
  MockInventoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createItem(_i4.InventoryItem? item) => (super.noSuchMethod(
        Invocation.method(
          #createItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.InventoryItem?> getItemById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getItemById,
          [id],
        ),
        returnValue: _i3.Future<_i4.InventoryItem?>.value(),
      ) as _i3.Future<_i4.InventoryItem?>);

  @override
  _i3.Future<List<_i4.InventoryItem>> fetchItems() => (super.noSuchMethod(
        Invocation.method(
          #fetchItems,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.InventoryItem>>.value(<_i4.InventoryItem>[]),
      ) as _i3.Future<List<_i4.InventoryItem>>);

  @override
  _i3.Future<void> updateItem(_i4.InventoryItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeItem,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
