/// Curated offline suggestions for a yarn-craft-led maker workflow.
/// Crochet and knitting appear first; users can still add their own values.
class SelectionOptions {
  static const List<String> finishedItemCategories = [
    'Finished Crochet Makes',
    'Finished Knitted Makes',
    'Finished Woven Makes',
    'Finished Sewn Makes',
    'Finished Embroidered Makes',
    'Finished Craft Kit',
    'Other Finished Make',
  ];

  static const List<String> materialStockCategories = [
    'Yarn & Fibre',
    'Crochet Hooks',
    'Knitting Needles',
    'Stitch Markers & Counters',
    'Yarn Tools & Accessories',
    'Patterns & Project Notes',
    'Blocking & Finishing',
    'Amigurumi Components',
    'Toy Stuffing & Safety Eyes',
    'Buttons & Fastenings',
    'Bag Hardware & Handles',
    'Embroidery & Cross-stitch',
    'Thread & Floss',
    'Sewing Notions',
    'Fabric & Textiles',
    'Quilting Supplies',
    'Weaving & Macramé',
    'Dyes & Inks',
    'Adhesives & Tapes',
    'Paper & Card',
    'Paint & Pigment',
    'Beads & Jewellery Findings',
    'Leather & Hide',
    'Wood & Timber',
    'Ceramics & Clay',
    'Glass & Mosaic',
    'Moulds & Resin',
    'Tools & Equipment',
    'Packaging & Labels',
    'Safety Equipment',
  ];

  static const List<String> inventoryCategories = [
    'Finished Crochet Makes',
    'Finished Knitted Makes',
    'Yarn & Fibre',
    'Crochet Hooks',
    'Knitting Needles',
    'Stitch Markers & Counters',
    'Yarn Tools & Accessories',
    'Patterns & Project Notes',
    'Blocking & Finishing',
    'Amigurumi Components',
    'Toy Stuffing & Safety Eyes',
    'Buttons & Fastenings',
    'Bag Hardware & Handles',
    'Embroidery & Cross-stitch',
    'Thread & Floss',
    'Sewing Notions',
    'Fabric & Textiles',
    'Quilting Supplies',
    'Weaving & Macramé',
    'Dyes & Inks',
    'Adhesives & Tapes',
    'Paper & Card',
    'Paint & Pigment',
    'Beads & Jewellery Findings',
    'Leather & Hide',
    'Wood & Timber',
    'Ceramics & Clay',
    'Glass & Mosaic',
    'Moulds & Resin',
    'Tools & Equipment',
    'Packaging & Labels',
    'Safety Equipment',
  ];

  static const List<String> storageLocations = [
    'Yarn Shelf',
    'Yarn Basket',
    'Project Bag',
    'WIP Basket',
    'Hook Case',
    'Needle Case',
    'Pattern Folder',
    'Notions Tin',
    'Craft Room',
    'Studio',
    'Worktable',
    'Desk Drawer',
    'Display Shelf',
    'Mobile Craft Bag',
    'Shed / Workshop',
    'Loft / Attic',
    'Under-bed Storage',
    'Wardrobe',
    'Box A',
    'Box B',
    'Box C',
    'Drawer 1',
    'Drawer 2',
    'Shelf 1',
    'Shelf 2',
  ];

  static const List<String> craftTypes = [
    'Crochet',
    'Amigurumi',
    'Tunisian Crochet',
    'Filet Crochet',
    'Crochet Garments',
    'Crochet Homeware',
    'Knitting',
    'Lace Knitting',
    'Sock Knitting',
    'Colourwork Knitting',
    'Spinning',
    'Weaving',
    'Macramé',
    'Embroidery',
    'Cross-stitch',
    'Sewing',
    'Quilting',
    'Textile Dyeing',
    'Toy Making',
    'Jewellery Making',
    'Paper Craft',
    'Card Making',
    'Candle Making',
    'Ceramics',
    'Pottery',
    'Resin Art',
    'Painting',
    'Woodworking',
  ];

  static const List<String> supplyUnits = [
    'ball',
    'cake',
    'cone',
    'hank',
    'skein',
    'spool',
    'reel',
    'pair',
    'piece',
    'pack',
    'bag',
    'bundle',
    'button',
    'gram',
    'kilogram',
    'metre',
    'centimetre',
    'yard',
    'millilitre',
    'litre',
    'sheet',
    'roll',
  ];
}
