/// Curated offline suggestions for ArtisanArc's crochet-first maker workflow.
/// The crochet choices lead every searchable picker; closely related yarn crafts
/// remain available for makers who combine techniques or sell mixed collections.
class SelectionOptions {
  static const List<String> finishedItemCategories = [
    'Crochet Amigurumi & Plush',
    'Crochet Wearables',
    'Crochet Accessories',
    'Crochet Bags & Storage',
    'Crochet Homeware',
    'Crochet Baby & Children',
    'Crochet Seasonal & Gifts',
    'Crochet Appliqués & Embellishments',
    'Crochet Kits',
    'Knitted Makes',
    'Other Fibre Make',
  ];

  static const List<String> materialStockCategories = [
    'Yarn — Cotton & Plant Fibre',
    'Yarn — Wool & Animal Fibre',
    'Yarn — Acrylic & Synthetic',
    'Yarn — Blends & Speciality',
    'Yarn — Thread, Lace & Mini Skeins',
    'Crochet Hooks',
    'Tunisian Crochet Hooks',
    'Ergonomic Hook Handles & Grips',
    'Stitch Markers & Row Counters',
    'Measuring, Gauge & Swatch Tools',
    'Yarn Needles & Finishing Tools',
    'Blocking & Shaping Supplies',
    'Amigurumi Safety Eyes & Noses',
    'Amigurumi Stuffing & Weights',
    'Amigurumi Joints, Wire & Armature',
    'Buttons, Zips & Fastenings',
    'Bag Hardware, Handles & Straps',
    'Lining, Fabric & Sewing Notions',
    'Embroidery Details & Thread',
    'Patterns & Project References',
    'Packaging, Labels & Care Cards',
    'Photography & Display Supplies',
    'Tools & Equipment',
    'Knitting Needles & Accessories',
    'Weaving, Spinning & Macramé Supplies',
    'Other Craft Material',
  ];

  static const List<String> inventoryCategories = [
    ...finishedItemCategories,
    ...materialStockCategories,
  ];

  static const List<String> storageLocations = [
    'Yarn Shelf',
    'Yarn Cubby',
    'Yarn Basket',
    'Project Bag',
    'WIP Basket',
    'Hook Case',
    'Notions Tin',
    'Blocking Board Storage',
    'Pattern Folder',
    'Craft Room',
    'Studio',
    'Worktable',
    'Display Shelf',
    'Market Crate',
    'Market Table Box',
    'Packaging Station',
    'Mobile Craft Bag',
    'Under-bed Storage',
    'Wardrobe',
    'Drawer 1',
    'Drawer 2',
    'Shelf 1',
    'Shelf 2',
  ];

  static const List<String> craftTypes = [
    'Crochet',
    'Amigurumi',
    'Crochet Wearables',
    'Crochet Accessories',
    'Crochet Homeware',
    'Crochet Bags',
    'Baby & Children Crochet',
    'Seasonal Crochet',
    'Tunisian Crochet',
    'Filet Crochet',
    'Tapestry Crochet',
    'Mosaic Crochet',
    'Granny Square Crochet',
    'Irish Lace Crochet',
    'Freeform Crochet',
    'Knitting',
    'Sock Knitting',
    'Lace Knitting',
    'Colourwork Knitting',
    'Spinning',
    'Weaving',
    'Macramé',
    'Embroidery',
    'Cross-stitch',
    'Sewing & Lining',
    'Textile Dyeing',
    'Toy Making',
    'Other Fibre Craft',
  ];

  static const List<String> supplyUnits = [
    'ball',
    'cake',
    'cone',
    'hank',
    'skein',
    'mini skein',
    'spool',
    'reel',
    'pair',
    'piece',
    'set',
    'pack',
    'bag',
    'bundle',
    'motif',
    'panel',
    'button',
    'eye',
    'gram',
    'kilogram',
    'metre',
    'centimetre',
    'yard',
    'inch',
    'sheet',
    'roll',
  ];

  static const List<String> yarnWeights = [
    'Thread',
    'Lace',
    'Super Fine / Fingering',
    'Fine / Sport',
    'Light / DK',
    'Medium / Worsted',
    'Bulky / Chunky',
    'Super Bulky',
    'Jumbo',
    'Unknown / Mixed',
  ];

  static const List<String> yarnFibres = [
    'Cotton',
    'Mercerised Cotton',
    'Bamboo',
    'Linen',
    'Hemp',
    'Wool',
    'Merino Wool',
    'Alpaca',
    'Mohair',
    'Silk',
    'Acrylic',
    'Polyester',
    'Nylon',
    'Mixed Fibre',
    'Recycled Fibre',
    'Other Fibre',
  ];

  static const List<String> crochetHookSizes = [
    '0.60 mm',
    '0.75 mm',
    '1.00 mm',
    '1.25 mm',
    '1.50 mm',
    '1.75 mm',
    '2.00 mm',
    '2.25 mm',
    '2.50 mm',
    '2.75 mm',
    '3.00 mm',
    '3.25 mm',
    '3.50 mm',
    '3.75 mm',
    '4.00 mm',
    '4.50 mm',
    '5.00 mm',
    '5.50 mm',
    '6.00 mm',
    '6.50 mm',
    '7.00 mm',
    '8.00 mm',
    '9.00 mm',
    '10.00 mm',
    '12.00 mm',
    '15.00 mm',
  ];
}
