/// Curated offline suggestions for common craft-inventory workflows.
/// Users can still create their own values where a custom choice is needed.
class SelectionOptions {
  static const List<String> inventoryCategories = [
    'Adhesives & Tapes',
    'Beads & Findings',
    'Buttons & Fastenings',
    'Canvas & Surfaces',
    'Ceramics & Clay',
    'Cutting Tools',
    'Dyes & Inks',
    'Electronics & Components',
    'Embroidery & Cross-stitch',
    'Fabric & Textiles',
    'Fasteners & Hardware',
    'Floral & Botanical',
    'Frames & Display',
    'Glass & Mosaic',
    'Jewellery Making',
    'Leather & Hide',
    'Markers & Pens',
    'Metal & Wire',
    'Mixed Media',
    'Moulds & Resin',
    'Needles & Hooks',
    'Packaging & Labels',
    'Paint & Pigment',
    'Paper & Card',
    'Patterns & Templates',
    'Printing & Stamping',
    'Safety Equipment',
    'Sewing Notions',
    'Tools & Equipment',
    'Vinyl & Heat Transfer',
    'Wood & Timber',
    'Wool, Yarn & Thread',
  ];

  static const List<String> storageLocations = [
    'Craft Room',
    'Desk Drawer',
    'Display Shelf',
    'Garage',
    'Kitchen Cupboard',
    'Living Room Storage',
    'Loft / Attic',
    'Mobile Craft Bag',
    'Office Cabinet',
    'Shed / Workshop',
    'Studio',
    'Under-bed Storage',
    'Utility Room',
    'Wardrobe',
    'Worktable',
    'Box A',
    'Box B',
    'Box C',
    'Drawer 1',
    'Drawer 2',
    'Drawer 3',
    'Shelf 1',
    'Shelf 2',
    'Shelf 3',
  ];

  static const List<String> craftTypes = [
    'Bookbinding',
    'Calligraphy',
    'Candle Making',
    'Card Making',
    'Ceramics',
    'Crochet',
    'Cross-stitch',
    'Decoupage',
    'Embroidery',
    'Floral Craft',
    'Glass Fusing',
    'Jewellery Making',
    'Knitting',
    'Leathercraft',
    'Macramé',
    'Mosaic',
    'Painting',
    'Paper Craft',
    'Pottery',
    'Quilting',
    'Resin Art',
    'Sculpture',
    'Sewing',
    'Soap Making',
    'Spinning',
    'Textile Dyeing',
    'Toy Making',
    'Weaving',
    'Woodworking',
  ];

  static const List<String> supplyUnits = [
    'bag',
    'bottle',
    'box',
    'bundle',
    'card',
    'cone',
    'gram',
    'kilogram',
    'litre',
    'metre',
    'millilitre',
    'pack',
    'pair',
    'piece',
    'reel',
    'roll',
    'sheet',
    'skein',
    'spool',
    'tube',
    'yard',
  ];
}
